# Generated by Django 4.2.4 on 2023-10-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choices', models.CharField(choices=[('being active', 'Being active'), ('ambition', 'Ambition'), ('confidence', 'Confidence'), ('positivity', 'Positivity'), ('bls', 'BLS'), ('feminismt', 'Feminismt'), ('human rights', 'Human Rights'), ('environmentalism', 'Environmentalism'), ('beaches', 'Beaches'), ('camping', 'Camping'), ('spa', 'Spa'), ('country escape', 'Country Escape'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('sci-fi', 'Sci-fi'), ('anime', 'Anime')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=120, verbose_name='language')),
            ],
        ),
    ]
