# Generated by Django 4.2.5 on 2023-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='first name')),
                ('last_name', models.CharField(max_length=120, verbose_name='last name')),
                ('gender', models.CharField(max_length=120, verbose_name='gender')),
                ('DOB', models.DateField(verbose_name='date of birth')),
                ('location_state', models.CharField(max_length=120, verbose_name='state')),
                ('location_city', models.CharField(max_length=120, verbose_name='city')),
                ('university', models.CharField(max_length=120, verbose_name='university')),
                ('course', models.CharField(max_length=120, verbose_name='course')),
            ],
        ),
    ]
