# Generated by Django 4.2.4 on 2023-08-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'interests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_filename', models.CharField(max_length=255)),
                ('photo_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventInvitedUsers',
            fields=[
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='temanuni.events')),
            ],
            options={
                'db_table': 'event_invited_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventUsersDeclined',
            fields=[
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='temanuni.events')),
            ],
            options={
                'db_table': 'event_users_declined',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventUsersGoing',
            fields=[
                ('event_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='temanuni.events')),
            ],
            options={
                'db_table': 'event_users_going',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='temanuni.user')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileInterests',
            fields=[
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='temanuni.profile')),
            ],
            options={
                'db_table': 'profile_interests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileLanguages',
            fields=[
                ('profile_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='temanuni.profile')),
            ],
            options={
                'db_table': 'profile_languages',
                'managed': False,
            },
        ),
    ]
