# Generated by Django 4.2.4 on 2023-08-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interest_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('interest', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.interests')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_filename', models.CharField(max_length=255)),
                ('photo_path', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='temanuni.user')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='temanuni.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventUsersGoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.user')),
            ],
        ),
        migrations.CreateModel(
            name='EventUsersDeclined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.user')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.user'),
        ),
        migrations.CreateModel(
            name='EventInvitedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temanuni.user')),
            ],
        ),
    ]
