# Generated by Django 4.2.4 on 2023-09-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temanuni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_interest', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('user2_interest', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
            options={
                'db_table': 'friends',
                'managed': False,
            },
        ),
    ]
