# Generated by Django 4.2.4 on 2023-09-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temanuni', '0002_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'managed': True},
        ),
    ]
