# Generated by Django 4.2.4 on 2023-09-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temanuni', '0003_alter_friends_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'managed': False},
        ),
    ]
